In [1]:
with open('textLog.txt') as file:
        data= []
        game_data=data
data_df = pd.DataFrame(game_data)
return data_df

IOError: [Errno 2] No such file or directory: 'textLog.txt'

In [2]:
import pandas as pd
import numpy as np

with open('TestLog.txt') as file:
        i=0
        data=[]
        data_df={}
        for line in file:
            if(line=='New Iteration'):
                i=0;
                data_df = data_new + "i"
                
                df_new= df[:('New Iteration'),:]
                i++
            else:
            
           
               s=line.split()
               data.append(s)
data_df = pd.DataFrame(data)
data_df.columns= ['Distance','Vertical','Horizontal']
data_df

SyntaxError: invalid syntax (<ipython-input-2-143205a4c681>, line 14)

In [3]:
umpy as np

with open('TestLog.txt') as file:
        i=0
        data=[]
        data_df={}
        for line in file:
            if(line=='New Iteration'):
                i=0;
                data_df = data_new + "i"
                
                df_new= df[:('New Iteration'),:]
                i++
            else:
            
           
               s=line.split()
               data.append(s)
data_df = pd.DataFrame(data)
data_df.columns= ['Distance','Vertical','Horizontal']
data_df

SyntaxError: invalid syntax (<ipython-input-3-9b54c141e84c>, line 1)

In [4]:
import pandas as pd
import numpy as np

with open('TestLog.txt') as file:
        i=0
        data=[]
        data_df={}
        for line in file:
            if(line=='New Iteration'):
                i=0;
                data_df = data_new + "i"
                
                df_new= df[:('New Iteration'),:]
                i++
            else:
            
           
               s=line.split()
               data.append(s)
data_df = pd.DataFrame(data)
data_df.columns= ['Distance','Vertical','Horizontal']
data_df

SyntaxError: invalid syntax (<ipython-input-4-75c481e8599d>, line 14)

In [5]:
import pandas as pd
import numpy as np

with open('TestLog.txt') as file:
        i=0
        data=[]
        data_df={}
        for line in file:
            if(line=='New Iteration'):
                i=0;
                df_new= df[:('NewIteration'),:]
                data_df = data_new + "i"
                i+=1
            else:
                s=line.split()
                data.append(s)
data_df = pd.DataFrame(data)
data_df.columns= ['Distance','Vertical','Horizontal']
data_df

      Distance   Vertical Horizontal
0          New  Iteration       None
1         None       None       None
2            0          0          0
3    0.3300053          0          0
4    0.3300053          1          0
5     1.053045          1          0
6     1.152244          1          0
7      1.22336          1          0
8     1.325096          1          0
9     1.397977          1          0
10    1.461679          1          0
11    1.530463          1          0
12    1.610063          1          0
13    1.670707          1          0
14    1.728707          1          0
15    1.799538          1          0
16    1.869697          1          0
17    1.942356          1          0
18    2.010142          1          0
19    2.080122          1          0
20    2.151314          1          0
21    2.217636          1          0
22    2.284403          1          0
23    2.342914          1          0
24    2.403087          1          0
25    2.459238          1          0
26    2.523252          1          0
27    2.597963          1          0
28    2.698191          1          0
29    2.780802          1          0
..         ...        ...        ...
585   18.43833          1          0
586   18.48521          1          0
587   18.53321          1          0
588   18.58707          1          0
589   18.62646          1          0
590    18.6746          1          0
591   18.71922          1          0
592   18.76337          1          0
593   18.80475          1          0
594   18.84214          1          0
595   18.87842          1          0
596   18.91989          1          0
597   18.96793          1          0
598   19.01614          1          0
599    19.0684          1          0
600   19.11937          1          0
601   19.16699          1          0
602   19.21921          1          0
603   19.27028          1          0
604   19.31319          1          0
605   19.36663          1          0
606    19.4169          1          0
607   19.46116          1          0
608   19.50718          1          0
609   19.54624          1          0
610   19.58671          1          0
611   19.63769          1          0
612   19.68253          1          0
613   19.72014          1          0
614   19.76713          1          0

[615 rows x 3 columns]

In [8]:
import pandas as pd
import numpy as np

with open('TestLog.txt') as file:
        
        """for line in file:
            if(line=='New Iteration'):
                i=0;
                df_new= df[:('NewIteration'),:]
                data_df = data_new + "i"
                i+=1
            else:
                s=line.split()
                data.append(s)"""
i=0
data=[]
data_df={}
df_new= df[:'NewIteration',:]
data_df = data_new + "i"
i+=1
data_df = pd.DataFrame(data)
data_df.columns= ['Distance','Vertical','Horizontal']
data_df

NameError: name 'df' is not defined